const MAX_PRESTO_SEARCH_RESULTS = 1000;

const HTTP_STATUS_BAD_REQUEST = 400;
const HTTP_STATUS_OK = 200;
const HTTP_STATUS_NO_CONTENT = 204;

export {
    HTTP_STATUS_BAD_REQUEST,
    HTTP_STATUS_NO_CONTENT,
    HTTP_STATUS_OK,
    MAX_PRESTO_SEARCH_RESULTS,
};
