{{- if .Values.queue.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clp-package.fullname" . }}-queue
  labels:
    {{- include "clp-package.labels" . | nindent 4 }}
    app.kubernetes.io/component: queue
spec:
  serviceName: {{ include "clp-package.fullname" . }}-queue
  replicas: 1
  selector:
    matchLabels:
      {{- include "clp-package.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: queue
  template:
    metadata:
      labels:
        {{- include "clp-package.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: queue
    spec:
      serviceAccountName: {{ include "clp-package.serviceAccountName" . }}
      securityContext:
        {{- include "clp-package.thirdPartySecurityContext" . | nindent 8 }}
      containers:
      - name: rabbitmq
        image: "{{ .Values.queue.image.repository }}:{{ .Values.queue.image.tag }}"
        imagePullPolicy: {{ include "clp-package.imagePullPolicy" . }}
        ports:
        - name: amqp
          containerPort: 5672
          protocol: TCP
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "clp-package.fullname" . }}-secrets
              key: queue-username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "clp-package.fullname" . }}-secrets
              key: queue-password
        - name: RABBITMQ_LOGS
          value: /var/log/rabbitmq/rabbitmq.log
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - check_running
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - check_running
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /var/log/rabbitmq
        resources:
          {{- toYaml .Values.queue.resources | nindent 10 }}
  {{- if .Values.queue.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.queue.persistence.storageClass }}
      storageClassName: {{ .Values.queue.persistence.storageClass | quote }}
      {{- else if .Values.global.storageClass }}
      storageClassName: {{ .Values.global.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.queue.persistence.size }}
  {{- else }}
  volumes:
  - name: logs
    emptyDir: {}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clp-package.fullname" . }}-queue
  labels:
    {{- include "clp-package.labels" . | nindent 4 }}
    app.kubernetes.io/component: queue
spec:
  type: {{ .Values.queue.service.type }}
  ports:
  - port: {{ .Values.queue.service.port }}
    targetPort: amqp
    protocol: TCP
    name: amqp
  selector:
    {{- include "clp-package.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: queue
  clusterIP: None
{{- end }}
