apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clp-package.fullname" . }}-secrets
  labels:
    {{- include "clp-package.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database credentials
  db-username: {{ .Values.database.auth.username | quote }}
  db-password: {{ .Values.database.auth.password | required "database.auth.password is required" | quote }}
  db-root-password: {{ .Values.database.auth.rootPassword | required "database.auth.rootPassword is required" | quote }}

  # Queue credentials
  queue-username: {{ .Values.queue.auth.username | quote }}
  queue-password: {{ .Values.queue.auth.password | required "queue.auth.password is required" | quote }}

  # Redis credentials
  redis-password: {{ .Values.redis.auth.password | required "redis.auth.password is required" | quote }}

  {{- if .Values.aws.enabled }}
  # AWS credentials (optional)
  aws-access-key-id: {{ .Values.aws.accessKeyId | quote }}
  aws-secret-access-key: {{ .Values.aws.secretAccessKey | quote }}
  {{- end }}
