services:
  clp-runtime:
    hostname: "clp_runtime"
    image: "${CLP_PACKAGE_CONTAINER_IMAGE_REF:-clp-package}"
    logging:
      driver: "local"
    stdin_open: true
    tty: true
    user: "${CLP_FIRST_PARTY_SERVICE_UID_GID:-1000:999}"
    environment:
      HOME: "${HOME}"
      CLP_HOME: "${CLP_HOME}"
      CLP_PWD_HOST: "${CLP_PWD_HOST:-${PWD}}"
    volumes:
      - type: "bind"
        source: "${CLP_DOCKER_PLUGIN_DIR}"
        target: "/usr/local/lib/docker/cli-plugins"
        read_only: true
      - type: "bind"
        source: "${CLP_DOCKER_SOCK_PATH}"
        target: "/var/run/docker.sock"
      - type: "bind"
        source: "${CLP_HOME}"
        target: "${CLP_HOME}"
      - type: "bind"
        source: "/"
        target: "/mnt/host"
      - type: "bind"
        source: "/usr/bin/docker"
        target: "/usr/bin/docker"
        read_only: true
