name: "clp-execution-image-build"
description: "Builds a container image that contains the dependencies necessary
to run the CLP package."

inputs:
  containerImageRegistry:
    default: "ghcr.io"
    description: "Container Image Registry"
    required: false
  containerImageRegistryUsername:
    default: "${{github.actor}}"
    description: "Container Image Registry Username"
    required: false
  containerImageRegistryPassword:
    default: ""
    description: "Container Image Registry Password"
    required: false
  platformId:
    description: "Platform ID of the container. e.g., ubuntu."
    required: true
  platformVersionId:
    description: "Platform VERSION_ID / VERSION_CODENAME of the container.
      e.g., jammy, focal."
    required: true

runs:
  using: "composite"
  steps:
    - uses: "docker/login-action@v3"
      with:
        registry: "${{inputs.containerImageRegistry}}"
        username: "${{inputs.containerImageRegistryUsername}}"
        password: "${{inputs.containerImageRegistryPassword}}"

    - id: "sanitization"
      shell: "bash"
      run: |
        # Docker doesn't support repository names with uppercase characters, so we convert the
        # name to lowercase here.
        echo "REPOSITORY=$(echo '${{github.repository}}' | tr '[:upper:]' '[:lower:]')" \
          >> "$GITHUB_OUTPUT"

    - id: "meta"
      uses: "docker/metadata-action@v5"
      with:
        images: "${{inputs.containerImageRegistry}}/${{steps.sanitization.outputs.REPOSITORY}}\
          /clp-execution-x86-${{inputs.platformId}}-${{inputs.platformVersionId}}"

    - if: "github.event_name != 'pull_request' && github.ref == 'refs/heads/main'"
      uses: "docker/build-push-action@v5"
      with:
        context: "./"
        file: "./tools/docker-images/\
          clp-execution-base-${{inputs.platformId}}-${{inputs.platformVersionId}}/Dockerfile"
        push: true
        tags: "${{steps.meta.outputs.tags}}"
        labels: "${{steps.meta.outputs.labels}}"
