name: "clp-execution-image-build"
description: "Builds a container image that contains the dependencies necessary
to run the CLP package."

inputs:
  dockerfilePath:
    description: "Path to the Dockerfile."
    required: true
  platformId:
    description: "Platform ID of the container. e.g., ubuntu."
    required: true
  platformVersionId:
    description: "Platform VERSION_ID / VERSION_CODENAME of the container. 
      e.g., jammy, focal."
    required: true

env:
  CONTAINER_IMAGE_REGISTRY: "ghcr.io"

runs:
  using: "composite"
  steps:
    - uses: "actions/checkout@v3"
      with:
        submodules: "recursive"

    - name: "Workaround actions/runner-images/issues/6775"
      shell: "bash"
      run: "chown $(id -u):$(id -g) -R ."

    - uses: "docker/login-action@v3"
      with:
        registry: "${{env.CONTAINER_IMAGE_REGISTRY}}"
        username: "${{github.actor}}"
        password: "${{secrets.GITHUB_TOKEN}}"

    - id: "sanitization"
      shell: "bash"
      run: |
        # Docker doesn't support repository names with uppercase characters, so we convert the
        # name to lowercase here.
        echo "REPOSITORY=$(echo '${{github.repository}}' | tr '[:upper:]' '[:lower:]')" \
          >> "$GITHUB_OUTPUT"

    - id: "meta"
      uses: "docker/metadata-action@v5"
      with:
        images: "${{env.CONTAINER_IMAGE_REGISTRY}}/${{steps.sanitization.outputs.REPOSITORY}}\
          /clp-execution-x86-${{inputs.platformId}}-${{inputs.platformVersionId}}"

    - if: "github.event_name != 'pull_request' && github.ref == 'refs/heads/main'"
      uses: "docker/build-push-action@v5"
      with:
        context: "./"
        file: "./tools/docker-images/\
          clp-execution-base-${{inputs.platformId}}-${{inputs.platformVersionId}}/Dockerfile"
        push: true
        tags: "${{steps.meta.outputs.tags}}"
        labels: "${{steps.meta.outputs.labels}}"
