name: "clp-execution-image-ubuntu-jammy"

on:
  pull_request:
    paths:
      - ".github/actions/clp-execution-image-build/action.yaml"
      - ".github/workflows/clp-execution-image-ubuntu-jammy.yaml"
      - "components/core/tools/scripts/lib_install/*"
      - "tools/docker-images/clp-execution-base-ubuntu-jammy/**"
  push:
    paths:
      - ".github/actions/clp-execution-image-build/action.yaml"
      - ".github/workflows/clp-execution-image-ubuntu-jammy.yaml"
      - "components/core/tools/scripts/lib_install/*"
      - "tools/docker-images/clp-execution-base-ubuntu-jammy/**"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Workaround actions/runner-images/issues/6775"
        shell: "bash"
        run: "chown $(id -u):$(id -g) -R ."

      - uses: "./.github/actions/clp-execution-image-build"
        with:
          containerImageRegistry: "ghcr.io"
          containerImageRegistryUsername: "${{github.actor}}"
          containerImageRegistryPassword: "${{secrets.GITHUB_TOKEN}}"
          platformId: "ubuntu"
          platformVersionId: "focal"
