name: "clp-execution-image-ubuntu-focal"

on:
  pull_request:
    paths:
      - ".github/actions/clp-execution-image-build/action.yaml"
      - ".github/workflows/clp-execution-image-ubuntu-focal.yaml"
      - "components/core/tools/scripts/lib_install/*"
      - "tools/docker-images/clp-execution-base-ubuntu-focal/**"
  push:
    paths:
      - ".github/actions/clp-execution-image-build/action.yaml"
      - ".github/workflows/clp-execution-image-ubuntu-focal.yaml"
      - "components/core/tools/scripts/lib_install/*"
      - "tools/docker-images/clp-execution-base-ubuntu-focal/**"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  build:
    uses: ".github/actions/clp-execution-image-build/action.yaml"
    with:
      dockerfilePath: "./tools/docker-images/clp-execution-base-ubuntu-focal/Dockerfile"
      platformId: "ubuntu"
      platformVersionId: "focal"
