name: "clp-package-image-build"

on:
  push:
  workflow_dispatch:

env:
  DEPS_IMAGE_NAME_PREFIX: "clp-core-dependencies-x86-"

jobs:
  filter-relevant-changes:
    name: "filter-relevant-changes"
    runs-on: "ubuntu-24.04"
    outputs:
      ubuntu_jammy_image_changed: "${{steps.filter.outputs.ubuntu_jammy_image}}"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          submodules: "recursive"

      - name: "Work around actions/runner-images/issues/6775"
        run: "chown $(id -u):$(id -g) -R ."
        shell: "bash"

      - name: "Filter relevant changes"
        uses: "dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36"
        id: "filter"
        with:
          # Consider changes between the current commit and `main`
          # NOTE: If a pull request changes one of the images, then we need to (1) build the image
          # (based on commits in the PR) and then (2) build CLP using the changed image. If a pull
          # request doesn't change an image, then we don't need to rebuild the image; instead we can
          # use the published image which is based on `main`. So when determining what files have
          # changed, we need to consider the delta between the current commit and `main` (rather
          # than the current and previous commits) in order to detect if we need to rebuild the
          # image (since it would be different from the published image).
          base: "main"
          filters: |
            ubuntu_jammy_image:
              - ".github/actions/**"
              - ".github/workflows/clp-core-build.yaml"
              - "components/core/tools/scripts/lib_install/*.sh"
              - "components/core/tools/docker-images/clp-env-base-ubuntu-jammy/**"
              - "components/core/tools/scripts/lib_install/ubuntu-jammy/**"
              - "tools/docker-images/clp-package-ubuntu-jammy/**"

  ubuntu-jammy-deps-image:
    name: "ubuntu-jammy-deps-image"
    needs: "filter-relevant-changes"
    runs-on: "ubuntu-24.04"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          submodules: "recursive"

      - name: "Work around actions/runner-images/issues/6775"
        run: "chown $(id -u):$(id -g) -R ."
        shell: "bash"

      - uses: "./.github/actions/clp-core-build-containers"
        env:
          OS_NAME: "ubuntu-jammy"
        with:
          image_name: "${{env.DEPS_IMAGE_NAME_PREFIX}}${{env.OS_NAME}}"
          docker_context: "components/core"
          docker_file: "components/core/tools/docker-images/clp-env-base-${{env.OS_NAME}}\
            /Dockerfile"
          push_deps_image: >-
            ${{github.event_name != 'pull_request' && github.ref == 'refs/heads/main'}}
          token: "${{secrets.GITHUB_TOKEN}}"

  ubuntu-jammy-package-image:
    name: "ubuntu-jammy-package-image"
    needs: "ubuntu-jammy-deps-image"
    runs-on: "ubuntu-24.04"
    env:
      OS_NAME: "ubuntu-jammy"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          submodules: "recursive"

      - name: "Workaround actions/runner-images/issues/6775"
        shell: "bash"
        run: "chown $(id -u):$(id -g) -R ."

      - name: "Build the package"
        uses: "./.github/actions/run-on-image"
        with:
          image_name: "${{env.DEPS_IMAGE_NAME_PREFIX}}${{env.OS_NAME}}"
          use_published_image: >-
            ${{needs.filter-relevant-changes.outputs.ubuntu_jammy_image_changed == 'false'
            || (github.event_name != 'pull_request' && github.ref == 'refs/heads/main')}}
          run_command: >-
            CLP_CORE_MAX_PARALLELISM_PER_BUILD_TASK=$(getconf _NPROCESSORS_ONLN) task package

      - uses: "./.github/actions/clp-image-build"
        with:
          image_type: "package"
          image_registry: "ghcr.io"
          image_registry_username: "${{github.actor}}"
          image_registry_password: "${{secrets.GITHUB_TOKEN}}"
          platform_id: "ubuntu"
          platform_version_id: "jammy"
